version: "3"
services:
  py-ana:
    container_name: atcoder-python-env
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/src
    working_dir: /src
    entrypoint: bash
    tty: true